import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

const bluuSuperstarFont = localFont({
   src: [
    {
      path: './assets/fonts/bluu-superstar/BluuSuuperstarRegular.ttf',
      weight: '400',
    },
    {
      path: './assets/fonts/bluu-superstar/BluuSuuperstarBold.ttf',
      weight: '600',
    },
    {
      path: './assets/fonts/bluu-superstar/BluuSuuperstarBlack.ttf',
      weight: '700',
    },
  ],
  variable: "--font-bluu",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bluuSuperstarFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
